# SPDX-License-Identifier: AGPL-3.0-or-later
# Rust formatting configuration for petalTongue
# Follows ecoPrimals wateringHole coding standards

edition = "2024"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
