//! Input Verification - Universal awareness of input reaching our sensors
//!
//! Parallel to output verification - for ALL inputs:
//! - Visual (camera, eye tracking, light sensors)
//! - Audio (microphone, voice)
//! - Haptic (touch, pressure, temperature sensors)
//! - Position (accelerometer, gyroscope, GPS)
//! - Any future input modality
//!
//! Key insight: Like proprioception, we need to know if our inputs
//! are actually receiving signals from the environment.

use anyhow::Result;
use petal_tongue_core::rendering_awareness::InteractivityState;
use std::time::{Duration, Instant};
use tracing::{debug, info, warn};

/// Input modality type (agnostic - no specific vendors)
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum InputModality {
    /// Visual input (camera, eye tracking)
    Visual,
    /// Audio input (microphone)
    Audio,
    /// Haptic input (touch, pressure, temperature)
    Haptic,
    /// Position input (accelerometer, gyroscope, GPS)
    Position,
    /// Keyboard input
    Keyboard,
    /// Pointer input (mouse, touchpad, stylus)
    Pointer,
    /// Generic input (unknown/future modality)
    Generic(String),
}

/// Input topology - where is the input coming from?
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputTopology {
    /// Direct from user (input device directly at user)
    Direct,

    /// Forwarded through intermediary (remote, network, virtualized)
    Forwarded,

    /// Synthetic (generated by software, not physical user)
    Synthetic,

    /// Ambient (environmental, not direct user input)
    Ambient,

    /// Unknown topology
    Unknown,
}

/// Input source quality - how reliable is this input?
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputQuality {
    /// High quality, direct, low latency
    High,

    /// Medium quality, some degradation
    Medium,

    /// Low quality, significant degradation
    Low,

    /// Quality unknown
    Unknown,
}

/// Input verification result for a single modality
#[derive(Debug, Clone)]
pub struct InputVerification {
    /// Which input modality is this for?
    pub modality: InputModality,

    /// Is input device available?
    pub device_available: bool,

    /// Is input being received?
    pub input_active: bool,

    /// Input topology (direct, forwarded, synthetic, ambient)
    pub topology: InputTopology,

    /// Can we confirm input is from intended source (user)?
    pub from_intended_source: bool,

    /// Input quality assessment
    pub quality: InputQuality,

    /// Evidence collected about input path
    pub evidence: Vec<String>,

    /// Last time we received input
    pub last_input: Option<Instant>,

    /// Current interactivity state
    pub interactivity: InteractivityState,

    /// Human-readable status
    pub status_message: String,

    /// Suggested action if there's an issue
    pub suggested_action: Option<String>,
}

impl InputVerification {
    /// Create a new unverified input
    pub fn unverified(modality: InputModality) -> Self {
        Self {
            modality,
            device_available: false,
            input_active: false,
            topology: InputTopology::Unknown,
            from_intended_source: false,
            quality: InputQuality::Unknown,
            evidence: vec![],
            last_input: None,
            interactivity: InteractivityState::Unconfirmed,
            status_message: "Input not yet verified".to_string(),
            suggested_action: None,
        }
    }

    /// Record that we received input
    pub fn record_input(&mut self) {
        self.input_active = true;
        self.last_input = Some(Instant::now());
        self.from_intended_source = true; // If we got input, it came from somewhere
        self.interactivity = InteractivityState::Active;
        self.status_message = format!("{:?} input active - receiving signals", self.modality);
        self.suggested_action = None;
    }

    /// Check if input is stale (no recent input)
    pub fn is_stale(&self, max_age: Duration) -> bool {
        self.last_input
            .map(|t| t.elapsed() > max_age)
            .unwrap_or(true)
    }

    /// Update interactivity based on recency
    pub fn update_interactivity(&mut self) {
        if let Some(last) = self.last_input {
            let elapsed = last.elapsed().as_secs_f32();
            self.interactivity = if elapsed < 5.0 {
                InteractivityState::Active
            } else if elapsed < 30.0 {
                InteractivityState::Recent
            } else if elapsed < 300.0 {
                InteractivityState::Idle
            } else {
                InteractivityState::Unconfirmed
            };
        } else {
            self.interactivity = InteractivityState::Unconfirmed;
        }
    }
}

/// Universal input verification system
pub struct InputVerificationSystem {
    /// Verifications for each active input modality
    verifications: std::collections::HashMap<InputModality, InputVerification>,

    /// Last time we updated verifications
    last_update: Instant,
}

impl InputVerificationSystem {
    /// Create a new input verification system
    pub fn new() -> Self {
        Self {
            verifications: std::collections::HashMap::new(),
            last_update: Instant::now(),
        }
    }

    /// Register an input modality for verification
    pub fn register_input(&mut self, modality: InputModality) {
        if !self.verifications.contains_key(&modality) {
            info!("📥 Registering input modality: {:?}", modality);
            self.verifications
                .insert(modality.clone(), InputVerification::unverified(modality));
        }
    }

    /// Record that we received input from a modality
    pub fn record_input(&mut self, modality: &InputModality) {
        if let Some(verification) = self.verifications.get_mut(modality) {
            verification.record_input();
            debug!("✅ {:?} input received", modality);
        } else {
            // Auto-register if we get input from an unregistered modality
            warn!("📥 Auto-registering input modality: {:?}", modality);
            let mut verification = InputVerification::unverified(modality.clone());
            verification.record_input();
            self.verifications.insert(modality.clone(), verification);
        }
    }

    /// Get verification for a specific modality
    pub fn get_verification(&self, modality: &InputModality) -> Option<&InputVerification> {
        self.verifications.get(modality)
    }

    /// Get all input verifications
    pub fn get_all_verifications(&self) -> Vec<&InputVerification> {
        self.verifications.values().collect()
    }

    /// Check if any inputs are inactive
    pub fn has_inactive_inputs(&self) -> bool {
        self.verifications.values().any(|v| !v.input_active)
    }

    /// Get most recent interaction time across all inputs
    pub fn most_recent_interaction(&self) -> Option<Instant> {
        self.verifications
            .values()
            .filter_map(|v| v.last_input)
            .max()
    }

    /// Get status summary
    pub fn get_status_summary(&self) -> String {
        let total = self.verifications.len();
        let active = self
            .verifications
            .values()
            .filter(|v| v.input_active)
            .count();
        let stale = self
            .verifications
            .values()
            .filter(|v| v.is_stale(Duration::from_secs(30)))
            .count();

        format!("Inputs: {}/{} active, {} stale", active, total, stale)
    }

    /// Perform periodic verification update
    pub fn update(&mut self) {
        let now = Instant::now();
        let elapsed = now.duration_since(self.last_update);

        // Only update every 5 seconds
        if elapsed < Duration::from_secs(5) {
            return;
        }

        self.last_update = now;

        // Update interactivity states
        for (modality, verification) in &mut self.verifications {
            verification.update_interactivity();

            if verification.is_stale(Duration::from_secs(300)) {
                warn!("⚠️  {:?} input is stale (no recent input)", modality);
                verification.status_message =
                    format!("{:?} input: No recent activity detected", modality);
                verification.suggested_action = Some(format!(
                    "Try using {:?} input to confirm it's working",
                    modality
                ));
            }
        }
    }
}

impl Default for InputVerificationSystem {
    fn default() -> Self {
        Self::new()
    }
}

/// Detect keyboard input topology
pub fn detect_keyboard_topology() -> (InputTopology, Vec<String>) {
    let mut evidence = Vec::new();

    // Check for SSH
    if std::env::var("SSH_CONNECTION").is_ok() {
        evidence.push("SSH connection detected - keyboard input forwarded".to_string());
        return (InputTopology::Forwarded, evidence);
    }

    // Check for physical keyboards
    if let Ok(entries) = std::fs::read_dir("/dev/input") {
        let kbd_devices: Vec<_> = entries
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().starts_with("event"))
            .collect();

        if !kbd_devices.is_empty() {
            evidence.push(format!("Found {} input devices", kbd_devices.len()));
        }
    }

    if evidence.is_empty() {
        evidence.push("No keyboard input detected".to_string());
        (InputTopology::Unknown, evidence)
    } else {
        (InputTopology::Direct, evidence)
    }
}

/// Detect pointer input topology
pub fn detect_pointer_topology() -> (InputTopology, Vec<String>) {
    let mut evidence = Vec::new();

    // Check for SSH with X11 forwarding
    if std::env::var("SSH_CONNECTION").is_ok() && std::env::var("DISPLAY").is_ok() {
        evidence.push("SSH with X11 forwarding - pointer input forwarded".to_string());
        return (InputTopology::Forwarded, evidence);
    }

    // Check for pointer devices
    if std::path::Path::new("/dev/input/mice").exists() {
        evidence.push("Mouse device detected".to_string());
    }

    if evidence.is_empty() {
        evidence.push("No pointer input detected".to_string());
        (InputTopology::Unknown, evidence)
    } else {
        (InputTopology::Direct, evidence)
    }
}
